# Generated by Django 4.0.5 on 2022-06-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_description_remove_user_post_addpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
