# Generated by Django 4.0.5 on 2022-06-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='add_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.addpost'),
            preserve_default=False,
        ),
    ]
