# Generated by Django 4.0.5 on 2022-06-03 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_likes_add_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='dislike',
            field=models.ManyToManyField(related_name='dislik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addpost',
            name='like',
            field=models.ManyToManyField(related_name='lik', to=settings.AUTH_USER_MODEL),
        ),
    ]
