# Generated by Django 4.0.5 on 2022-06-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_addpost_dislike_alter_addpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='dislike',
        ),
    ]
