# Generated by Django 4.0.5 on 2022-06-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_follower_follower_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
    ]
