# Generated by Django 4.0.5 on 2022-06-06 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comment_followers_delete_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='followers',
        ),
        migrations.AddField(
            model_name='addpost',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
