# Generated by Django 4.0.5 on 2022-06-06 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_comment_followers_addpost_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
